--
-- PostgreSQL database dump
--

-- Dumped from database version 14.11 (Homebrew)
-- Dumped by pg_dump version 14.15 (Homebrew)

-- Started on 2025-04-24 00:09:52 -03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE gerenciador_portfolio;
--
-- TOC entry 3682 (class 1262 OID 16791)
-- Name: gerenciador_portfolio; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE gerenciador_portfolio WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'C';


\connect gerenciador_portfolio

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16841)
-- Name: risco; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.risco (
    id_risco bigint NOT NULL,
    risco character varying(255)
);


--
-- TOC entry 217 (class 1259 OID 16840)
-- Name: risco_id_risco_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.risco ALTER COLUMN id_risco ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.risco_id_risco_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16815)
-- Name: status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.status (
    id_status bigint NOT NULL,
    ordem integer NOT NULL,
    status character varying(255)
);


--
-- TOC entry 215 (class 1259 OID 16814)
-- Name: status_id_status_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.status ALTER COLUMN id_status ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.status_id_status_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3676 (class 0 OID 16841)
-- Dependencies: 218
-- Data for Name: risco; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.risco VALUES (1, 'BAIXO');
INSERT INTO public.risco VALUES (2, 'MEDIO');
INSERT INTO public.risco VALUES (3, 'ALTO');


--
-- TOC entry 3674 (class 0 OID 16815)
-- Dependencies: 216
-- Data for Name: status; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.status VALUES (1, 1, 'em análise');
INSERT INTO public.status VALUES (2, 2, 'análise realizada');
INSERT INTO public.status VALUES (3, 3, 'análise aprovada');
INSERT INTO public.status VALUES (4, 4, 'iniciado');
INSERT INTO public.status VALUES (5, 5, 'planejado');
INSERT INTO public.status VALUES (6, 6, 'em andamento');
INSERT INTO public.status VALUES (7, 7, 'encerrado');
INSERT INTO public.status VALUES (8, 0, 'cancelado');


--
-- TOC entry 3686 (class 0 OID 16841)
-- Dependencies: 218
-- Name: risco_id_risco_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.risco_id_risco_seq', 3, true);


--
-- TOC entry 3687 (class 0 OID 0)
-- Dependencies: 215
-- Name: status_id_status_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.status_id_status_seq', 8, true);

-- Completed on 2025-04-24 00:09:53 -03

--
-- PostgreSQL database dump complete
--
